[package]
name = "jni"
version = "0.1.0"
authors = ["Josh Chase <josh@prevoty.com>"]
description = "Rust bindings to the JNI"
license = "MIT/Apache-2.0"
keywords = ["ffi", "jni", "java"]
repository = "https://github.com/prevoty/jni-rs"


[dependencies]
log = "0.3"
error-chain = "0.5"
combine = "2"
cesu8 = "1"

[features]
default = []

sys-only = []
