[package]
name = "jni"
version = "0.1.0"
authors = ["Josh Chase <jcjoshuachase@gmail.com>"]
description = "proof-of-concept callable from java lib"

[dependencies]
log = "0.3"
jni-sys = { path = "./jni-sys" }
error-chain = "0.5"
combine = "2"
cesu8 = "1"
