[package]
name = "jni"
version = "0.1.0"
authors = ["Josh Chase <jcjoshuachase@gmail.com>"]
description = "proof-of-concept callable from java lib"

[lib]
crate-type = ["dylib"]

[dependencies]
libc = "*"
